### ISSUE TITLE
#hit columns 

### ISSUE THREAD

**Issue by nina-zhuchkova** [korabelnikovadarya/Informatic.Team#2]
использование new_security не позволяет реализовать подход охранника вплотную к колоннам, возможно стоит попробовать проверять столкновение с Barrier через набор условий для каждого направления. Если охранник идет вправо и сталкивается с barrier, то нужно присваивать ему такую координату, чтобы он стоял вплотную к левой границе объекта, а не сбрасывать движение полностью. Аналогично для остальных направлений.

**Comment by korabelnikovadarya** [comment]
Немного модифицировали взаимодействие с колоннами и столами, внесли изменения в barriers.py, security.py, students.py
